import * as stylex from "@stylexjs/stylex";
import { colors, fontSize, fonts, space } from "../../theme/tokens.stylex";

/** Styles builder parts share: dense, sheet-like controls. */
export const parts = stylex.create({
  label: { fontSize: fontSize.caption },
  rolls: { display: "flex", flexWrap: "wrap", gap: space.x1 },
  roll: {
    paddingBlock: "2px",
    paddingInline: space.x2,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: fontSize.caption,
    cursor: "pointer",
  },
  dice: { color: colors.accent, fontFamily: fonts.numeric },
  choose: { display: "flex", flexDirection: "column", gap: space.x2 },
  search: { width: "100%" },
  options: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    maxHeight: "180px",
    overflowY: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
  },
  option: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
    paddingBlock: "3px",
    paddingInline: space.x2,
    borderWidth: 0,
    borderBottomWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 0,
    boxShadow: "none",
    backgroundColor: "transparent",
    color: colors.text,
    textAlign: "start",
    fontSize: fontSize.caption,
    cursor: "pointer",
  },
  optionFocused: { backgroundColor: colors.surfaceHover },
  mark: { color: colors.accent },
  offer: {
    display: "flex",
    flexDirection: "column",
    gap: space.x1,
    padding: space.x2,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.accent,
    fontSize: fontSize.caption,
  },
  preview: { display: "flex", flexDirection: "column", gap: space.x2 },
  unsupported: {
    paddingBlock: space.x1,
    paddingInline: space.x2,
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: colors.border,
    color: colors.textMuted,
    fontSize: fontSize.caption,
  },
});
