import type { SheetLayout } from "../sheet-layout";

/*
 * A fifth-edition (2024 rules) character on generic blocks. Ability modifiers, proficiency,
 * saves and skills are derived values the sheet shows and rolls use; the
 * player marks proficiency as pips (1 proficient, 2 expertise for skills).
 * Nothing is written back: hit points, slots and uses are marked by hand.
 */

const mods = [
  { key: "str_mod", label: "STR mod", expr: "floor((@str - 10) / 2)" },
  { key: "dex_mod", label: "DEX mod", expr: "floor((@dex - 10) / 2)" },
  { key: "con_mod", label: "CON mod", expr: "floor((@con - 10) / 2)" },
  { key: "int_mod", label: "INT mod", expr: "floor((@int - 10) / 2)" },
  { key: "wis_mod", label: "WIS mod", expr: "floor((@wis - 10) / 2)" },
  { key: "cha_mod", label: "CHA mod", expr: "floor((@cha - 10) / 2)" },
];
const saves = [
  { key: "str_save", label: "Strength save", expr: "@str_mod + @str_save_prof * @prof" },
  { key: "dex_save", label: "Dexterity save", expr: "@dex_mod + @dex_save_prof * @prof" },
  { key: "con_save", label: "Constitution save", expr: "@con_mod + @con_save_prof * @prof" },
  { key: "int_save", label: "Intelligence save", expr: "@int_mod + @int_save_prof * @prof" },
  { key: "wis_save", label: "Wisdom save", expr: "@wis_mod + @wis_save_prof * @prof" },
  { key: "cha_save", label: "Charisma save", expr: "@cha_mod + @cha_save_prof * @prof" },
];
const skills = [
  { key: "acrobatics_bonus", label: "Acrobatics", expr: "@dex_mod + @acrobatics * @prof" },
  {
    key: "animal_handling_bonus",
    label: "Animal Handling",
    expr: "@wis_mod + @animal_handling * @prof",
  },
  { key: "arcana_bonus", label: "Arcana", expr: "@int_mod + @arcana * @prof" },
  { key: "athletics_bonus", label: "Athletics", expr: "@str_mod + @athletics * @prof" },
  { key: "deception_bonus", label: "Deception", expr: "@cha_mod + @deception * @prof" },
  { key: "history_bonus", label: "History", expr: "@int_mod + @history * @prof" },
  { key: "insight_bonus", label: "Insight", expr: "@wis_mod + @insight * @prof" },
  { key: "intimidation_bonus", label: "Intimidation", expr: "@cha_mod + @intimidation * @prof" },
  { key: "investigation_bonus", label: "Investigation", expr: "@int_mod + @investigation * @prof" },
  { key: "medicine_bonus", label: "Medicine", expr: "@wis_mod + @medicine * @prof" },
  { key: "nature_bonus", label: "Nature", expr: "@int_mod + @nature * @prof" },
  { key: "perception_bonus", label: "Perception", expr: "@wis_mod + @perception * @prof" },
  { key: "performance_bonus", label: "Performance", expr: "@cha_mod + @performance * @prof" },
  { key: "persuasion_bonus", label: "Persuasion", expr: "@cha_mod + @persuasion * @prof" },
  { key: "religion_bonus", label: "Religion", expr: "@int_mod + @religion * @prof" },
  {
    key: "sleight_of_hand_bonus",
    label: "Sleight of Hand",
    expr: "@dex_mod + @sleight_of_hand * @prof",
  },
  { key: "stealth_bonus", label: "Stealth", expr: "@dex_mod + @stealth * @prof" },
  { key: "survival_bonus", label: "Survival", expr: "@wis_mod + @survival * @prof" },
];

export const dnd5eCharacter: SheetLayout = {
  system: "Fifth Edition (SRD 5.2)",
  name: "Character",
  derived: [
    { key: "prof", label: "Proficiency", expr: "ceil(@level / 4) + 1" },
    ...mods,
    ...saves,
    ...skills,
    { key: "initiative", label: "Initiative", expr: "@dex_mod" },
    { key: "passive_perception", label: "Passive Perception", expr: "10 + @perception_bonus" },
    { key: "spell_attack", label: "Spell attack", expr: "@prof + @spell_mod" },
    { key: "spell_dc", label: "Spell save DC", expr: "8 + @prof + @spell_mod" },
  ],
  pages: [
    {
      id: "character",
      title: "Character",
      blocks: [
        {
          id: "class",
          type: "entry",
          key: "class",
          entryType: "class",
          label: "Class",
          variant: "line",
          span: 3,
        },
        {
          id: "species",
          type: "entry",
          key: "species",
          entryType: "species",
          label: "Species",
          variant: "line",
          span: 3,
        },
        {
          id: "background",
          type: "entry",
          key: "background",
          entryType: "background",
          label: "Background",
          variant: "line",
          span: 3,
        },
        {
          id: "level",
          type: "stats",
          span: 3,
          items: [
            { key: "level", label: "Level" },
            { key: "prof", label: "Prof." },
          ],
        },
        {
          id: "abilities",
          type: "stats",
          variant: "boxes",
          items: [
            { key: "str", label: "STR" },
            { key: "dex", label: "DEX" },
            { key: "con", label: "CON" },
            { key: "int", label: "INT" },
            { key: "wis", label: "WIS" },
            { key: "cha", label: "CHA" },
          ],
        },
        {
          id: "modifiers",
          type: "stats",
          items: [
            { key: "str_mod", label: "STR mod", roll: "1d20 + @str_mod" },
            { key: "dex_mod", label: "DEX mod", roll: "1d20 + @dex_mod" },
            { key: "con_mod", label: "CON mod", roll: "1d20 + @con_mod" },
            { key: "int_mod", label: "INT mod", roll: "1d20 + @int_mod" },
            { key: "wis_mod", label: "WIS mod", roll: "1d20 + @wis_mod" },
            { key: "cha_mod", label: "CHA mod", roll: "1d20 + @cha_mod" },
          ],
        },
        {
          id: "health",
          type: "trackers",
          span: 3,
          items: [
            { key: "hp", label: "Hit Points", min: 0, max: 10 },
            { key: "temp_hp", label: "Temp HP", min: 0, max: 30, start: 0 },
            { key: "hit_dice", label: "Hit Dice", min: 0, max: 1 },
          ],
        },
        {
          id: "combat",
          type: "stats",
          span: 3,
          items: [
            { key: "ac", label: "AC" },
            { key: "initiative", label: "Initiative", roll: "1d20 + @initiative" },
            { key: "speed", label: "Speed" },
            { key: "passive_perception", label: "Passive Perc." },
          ],
        },
        {
          id: "death",
          type: "trackers",
          variant: "boxes",
          items: [
            { key: "death_successes", label: "Death save successes", min: 0, max: 3, start: 0 },
            { key: "death_failures", label: "Death save failures", min: 0, max: 3, start: 0 },
          ],
        },
        {
          id: "weapons",
          type: "list",
          key: "weapons",
          title: "Weapons",
          source: { entryType: "weapon" },
          roll: "1d20 + @row.attack",
          columns: [
            { key: "name", label: "Weapon", kind: "text" },
            { key: "attack", label: "Attack", kind: "number" },
            { key: "damage", label: "Damage", kind: "dice" },
            { key: "damage_type", label: "Type", kind: "text" },
            { key: "mastery", label: "Mastery", kind: "text" },
          ],
        },
        {
          id: "rolls",
          type: "rolls",
          items: [
            { label: "d20", dice: "1d20" },
            { label: "Advantage", dice: "1d20adv" },
            { label: "Disadvantage", dice: "1d20dis" },
          ],
        },
      ],
    },
    {
      id: "skills",
      title: "Skills",
      blocks: [
        {
          id: "saves",
          type: "stats",
          variant: "list",
          span: 2,
          items: [
            { key: "str_save", label: "Strength", roll: "1d20 + @str_save" },
            { key: "dex_save", label: "Dexterity", roll: "1d20 + @dex_save" },
            { key: "con_save", label: "Constitution", roll: "1d20 + @con_save" },
            { key: "int_save", label: "Intelligence", roll: "1d20 + @int_save" },
            { key: "wis_save", label: "Wisdom", roll: "1d20 + @wis_save" },
            { key: "cha_save", label: "Charisma", roll: "1d20 + @cha_save" },
          ],
        },
        {
          id: "skill-totals",
          type: "stats",
          variant: "list",
          span: 4,
          items: [
            { key: "acrobatics_bonus", label: "Acrobatics", roll: "1d20 + @acrobatics_bonus" },
            {
              key: "animal_handling_bonus",
              label: "Animal Handling",
              roll: "1d20 + @animal_handling_bonus",
            },
            { key: "arcana_bonus", label: "Arcana", roll: "1d20 + @arcana_bonus" },
            { key: "athletics_bonus", label: "Athletics", roll: "1d20 + @athletics_bonus" },
            { key: "deception_bonus", label: "Deception", roll: "1d20 + @deception_bonus" },
            { key: "history_bonus", label: "History", roll: "1d20 + @history_bonus" },
            { key: "insight_bonus", label: "Insight", roll: "1d20 + @insight_bonus" },
            {
              key: "intimidation_bonus",
              label: "Intimidation",
              roll: "1d20 + @intimidation_bonus",
            },
            {
              key: "investigation_bonus",
              label: "Investigation",
              roll: "1d20 + @investigation_bonus",
            },
            { key: "medicine_bonus", label: "Medicine", roll: "1d20 + @medicine_bonus" },
            { key: "nature_bonus", label: "Nature", roll: "1d20 + @nature_bonus" },
            { key: "perception_bonus", label: "Perception", roll: "1d20 + @perception_bonus" },
            { key: "performance_bonus", label: "Performance", roll: "1d20 + @performance_bonus" },
            { key: "persuasion_bonus", label: "Persuasion", roll: "1d20 + @persuasion_bonus" },
            { key: "religion_bonus", label: "Religion", roll: "1d20 + @religion_bonus" },
            {
              key: "sleight_of_hand_bonus",
              label: "Sleight of Hand",
              roll: "1d20 + @sleight_of_hand_bonus",
            },
            { key: "stealth_bonus", label: "Stealth", roll: "1d20 + @stealth_bonus" },
            { key: "survival_bonus", label: "Survival", roll: "1d20 + @survival_bonus" },
          ],
        },
        {
          id: "save-proficiency",
          type: "trackers",
          span: 2,
          items: [
            { key: "str_save_prof", label: "Strength save", min: 0, max: 1, start: 0 },
            { key: "dex_save_prof", label: "Dexterity save", min: 0, max: 1, start: 0 },
            { key: "con_save_prof", label: "Constitution save", min: 0, max: 1, start: 0 },
            { key: "int_save_prof", label: "Intelligence save", min: 0, max: 1, start: 0 },
            { key: "wis_save_prof", label: "Wisdom save", min: 0, max: 1, start: 0 },
            { key: "cha_save_prof", label: "Charisma save", min: 0, max: 1, start: 0 },
          ],
        },
        {
          id: "skill-proficiency",
          type: "trackers",
          span: 4,
          items: [
            { key: "acrobatics", label: "Acrobatics", min: 0, max: 2, start: 0 },
            { key: "animal_handling", label: "Animal Handling", min: 0, max: 2, start: 0 },
            { key: "arcana", label: "Arcana", min: 0, max: 2, start: 0 },
            { key: "athletics", label: "Athletics", min: 0, max: 2, start: 0 },
            { key: "deception", label: "Deception", min: 0, max: 2, start: 0 },
            { key: "history", label: "History", min: 0, max: 2, start: 0 },
            { key: "insight", label: "Insight", min: 0, max: 2, start: 0 },
            { key: "intimidation", label: "Intimidation", min: 0, max: 2, start: 0 },
            { key: "investigation", label: "Investigation", min: 0, max: 2, start: 0 },
            { key: "medicine", label: "Medicine", min: 0, max: 2, start: 0 },
            { key: "nature", label: "Nature", min: 0, max: 2, start: 0 },
            { key: "perception", label: "Perception", min: 0, max: 2, start: 0 },
            { key: "performance", label: "Performance", min: 0, max: 2, start: 0 },
            { key: "persuasion", label: "Persuasion", min: 0, max: 2, start: 0 },
            { key: "religion", label: "Religion", min: 0, max: 2, start: 0 },
            { key: "sleight_of_hand", label: "Sleight of Hand", min: 0, max: 2, start: 0 },
            { key: "stealth", label: "Stealth", min: 0, max: 2, start: 0 },
            { key: "survival", label: "Survival", min: 0, max: 2, start: 0 },
          ],
        },
        {
          id: "proficiencies",
          type: "text",
          key: "proficiencies",
          label: "Other proficiencies & languages",
        },
      ],
    },
    {
      id: "spells",
      title: "Spells",
      blocks: [
        {
          id: "casting",
          type: "stats",
          items: [
            { key: "spell_mod", label: "Spell ability mod" },
            { key: "spell_attack", label: "Spell attack", roll: "1d20 + @spell_attack" },
            { key: "spell_dc", label: "Save DC" },
          ],
        },
        {
          id: "slots",
          type: "trackers",
          variant: "boxes",
          items: [
            { key: "slots_1", label: "Level 1", min: 0, max: 4, start: 0 },
            { key: "slots_2", label: "Level 2", min: 0, max: 3, start: 0 },
            { key: "slots_3", label: "Level 3", min: 0, max: 3, start: 0 },
            { key: "slots_4", label: "Level 4", min: 0, max: 3, start: 0 },
            { key: "slots_5", label: "Level 5", min: 0, max: 3, start: 0 },
            { key: "slots_6", label: "Level 6", min: 0, max: 2, start: 0 },
            { key: "slots_7", label: "Level 7", min: 0, max: 2, start: 0 },
            { key: "slots_8", label: "Level 8", min: 0, max: 1, start: 0 },
            { key: "slots_9", label: "Level 9", min: 0, max: 1, start: 0 },
          ],
        },
        {
          id: "spell-list",
          type: "list",
          key: "spells",
          title: "Spells",
          source: { entryType: "spell" },
          columns: [
            { key: "prepared", label: "Prep.", kind: "check" },
            { key: "name", label: "Spell", kind: "text" },
            { key: "level", label: "Lvl", kind: "number" },
            { key: "casting", label: "Casting", kind: "text" },
            { key: "range", label: "Range", kind: "text" },
          ],
        },
      ],
    },
    {
      id: "features",
      title: "Features & Gear",
      blocks: [
        {
          id: "class-progression",
          type: "entry",
          key: "class",
          entryType: "class",
          variant: "progression",
          progression: { field: "levels", level: "level" },
        },
        {
          id: "feature-list",
          type: "list",
          key: "features",
          title: "Features",
          source: { entryType: "feature" },
          columns: [
            { key: "name", label: "Feature", kind: "text" },
            { key: "level", label: "Lvl", kind: "number" },
          ],
        },
        {
          id: "feat-list",
          type: "list",
          key: "feats",
          title: "Feats",
          source: { entryType: "feat" },
          columns: [
            { key: "name", label: "Feat", kind: "text" },
            { key: "category", label: "Category", kind: "text" },
          ],
        },
        {
          id: "gear",
          type: "list",
          key: "gear",
          title: "Equipment",
          source: { entryType: "gear" },
          columns: [
            { key: "name", label: "Item", kind: "text" },
            { key: "qty", label: "Qty", kind: "number" },
            { key: "weight", label: "Weight", kind: "text" },
          ],
        },
        {
          id: "magic-items",
          type: "list",
          key: "magic_items",
          title: "Magic Items",
          source: { entryType: "magic-item" },
          columns: [
            { key: "attuned", label: "Att.", kind: "check" },
            { key: "name", label: "Item", kind: "text" },
            { key: "rarity", label: "Rarity", kind: "text" },
          ],
        },
        {
          id: "coins",
          type: "stats",
          items: [
            { key: "cp", label: "CP" },
            { key: "sp", label: "SP" },
            { key: "ep", label: "EP" },
            { key: "gp", label: "GP" },
            { key: "pp", label: "PP" },
          ],
        },
        { id: "notes", type: "text", key: "notes", label: "Notes" },
      ],
    },
  ],
};
