import * as stylex from "@stylexjs/stylex";
import { colors, radii, space } from "../theme/tokens.stylex";

export const boardStyles = stylex.create({
  world: { height: "100dvh", minHeight: "480px", overflow: "hidden" },
  content: { flex: 1, minHeight: 0, display: "flex", flexDirection: "column" },
  header: { padding: space.x3, marginBottom: 0, backgroundColor: colors.surface },
  stage: { position: "relative", flex: 1, minHeight: 0, overflow: "hidden", isolation: "isolate" },
  board: { position: "absolute", inset: 0, backgroundColor: colors.canvas },
  viewport: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    touchAction: "none",
    outlineOffset: "-3px",
  },
  background: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    pointerEvents: "none",
    opacity: 0.75,
  },
  scene: { position: "absolute", left: 0, top: 0, transformOrigin: "0 0", willChange: "transform" },
  element: {
    position: "absolute",
    left: 0,
    top: 0,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: colors.text,
    textAlign: "left",
    touchAction: "none",
    userSelect: "none",
    borderRadius: radii.md,
  },
  selected: { outline: `2px solid ${colors.accent}`, outlineOffset: "4px" },
  image: { width: "100%", height: "100%", objectFit: "contain", pointerEvents: "none" },
  text: {
    width: "100%",
    height: "100%",
    padding: space.x5,
    backgroundColor: colors.surfaceRaised,
    whiteSpace: "pre-wrap",
    overflow: "hidden",
    boxShadow: "0 4px 24px #0002",
    borderRadius: radii.md,
    fontSize: "20px",
  },
  toolbar: {
    position: "absolute",
    zIndex: 2,
    bottom: space.x3,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: space.x2,
    padding: space.x3,
    maxWidth: "calc(100% - 16px)",
    width: "max-content",
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
  },
  inspector: {
    position: "absolute",
    zIndex: 2,
    top: space.x3,
    left: "50%",
    transform: "translateX(-50%)",
    width: "min(320px, calc(100% - 24px))",
    maxHeight: "60%",
    overflowY: "auto",
    padding: space.x4,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
    display: "flex",
    flexDirection: "column",
    gap: space.x3,
  },
  hint: {
    position: "absolute",
    top: "42%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    textAlign: "center",
    pointerEvents: "none",
    backgroundColor: colors.surface,
    padding: space.x5,
    borderRadius: radii.lg,
    width: "min(360px, 80%)",
  },
  panel: {
    position: "absolute",
    zIndex: 3,
    top: space.x3,
    bottom: "100px",
    width: "min(380px, calc(50% - 16px))",
    padding: space.x3,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
    overflowY: "auto",
    "@media (max-width: 700px)": { width: "calc(100% - 16px)", bottom: "150px" },
  },
  left: { left: space.x3 },
  right: { right: space.x3 },
  hidden: { display: "none" },
  tools: { maxHeight: "none", overflowY: "visible" },
  chat: { height: "100%", minHeight: 0 },
  status: { fontSize: "12px", color: colors.textMuted },
});
