import * as stylex from "@stylexjs/stylex";
import { colors, radii, space } from "../theme/tokens.stylex";

const focusFade = stylex.keyframes({
  "0%": { opacity: 1 },
  "65%": { opacity: 1 },
  "100%": { opacity: 0 },
});

export const boardStyles = stylex.create({
  scenePanels: {
    position: "fixed",
    inset: "auto",
    top: "80px",
    left: "50%",
    transform: "translateX(-50%)",
    margin: 0,
    maxHeight: "min(60dvh, 540px)",
    overflowY: "auto",
    width: "min(320px, calc(100vw - 32px))",
    boxSizing: "border-box",
    backgroundColor: colors.surface,
    color: colors.text,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: space.x2,
    whiteSpace: "normal",
    boxShadow: "0 4px 24px #0003",
  },
  prepBanner: { width: "100%", textAlign: "center", whiteSpace: "normal" },
  popoverTrigger: { display: "flex", alignItems: "center", gap: space.x2 },
  sceneName: {
    maxWidth: "110px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sceneBadge: {
    fontSize: "10px",
    fontWeight: 700,
    padding: "3px",
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.sm,
  },
  itemName: { flex: 1, minWidth: 0, overflowWrap: "anywhere", textAlign: "left" },
  nameInput: {
    width: "100%",
    boxSizing: "border-box",
    padding: space.x2,
    color: colors.text,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.sm,
  },
  panelContent: { display: "flex", flexDirection: "column", gap: space.x2, padding: space.x2 },
  panelItem: {
    display: "flex",
    flexDirection: "column",
    gap: space.x2,
    paddingBlock: space.x2,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  panelActions: { display: "flex", flexWrap: "wrap", gap: space.x2, alignItems: "center" },
  world: { height: "100dvh", minHeight: 0, overflow: "hidden" },
  content: { flex: 1, minHeight: 0, display: "flex", flexDirection: "column" },
  header: { padding: space.x3, marginBottom: 0, backgroundColor: colors.surface },
  stage: { position: "relative", flex: 1, minHeight: 0, overflow: "hidden", isolation: "isolate" },
  board: { position: "absolute", inset: 0, backgroundColor: colors.canvas },
  viewport: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    touchAction: "none",
    outlineOffset: "-3px",
    overscrollBehavior: "contain",
  },
  background: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    pointerEvents: "none",
    opacity: 0.75,
  },
  scene: { position: "absolute", left: 0, top: 0, transformOrigin: "0 0", willChange: "transform" },
  element: {
    position: "absolute",
    left: 0,
    top: 0,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: colors.text,
    textAlign: "left",
    touchAction: "none",
    userSelect: "none",
    borderRadius: radii.md,
  },
  textEditor: {
    zIndex: 1,
    outline: `2px solid ${colors.accent}`,
    outlineOffset: "2px",
    resize: "none",
    userSelect: "text",
    touchAction: "auto",
    overflow: "auto",
    lineHeight: "inherit",
    fontFamily: "inherit",
  },
  selection: {
    position: "absolute",
    outline: `2px solid ${colors.accent}`,
    pointerEvents: "none",
  },
  focusOutline: {
    position: "absolute",
    outline: `3px solid ${colors.accent}`,
    outlineOffset: "-3px",
    pointerEvents: "none",
    animationName: focusFade,
    animationDuration: "2.4s",
    animationFillMode: "forwards",
  },
  focusPrompt: {
    position: "absolute",
    zIndex: 4,
    top: "124px",
    left: "50%",
    transform: "translateX(-50%)",
    maxWidth: "calc(100% - 24px)",
    display: "flex",
    alignItems: "center",
    gap: space.x2,
    padding: space.x2,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
  },
  resizeHandle: {
    position: "absolute",
    transform: "translate(-50%, -50%)",
    width: { default: "24px", "@media (pointer: coarse)": "36px" },
    height: { default: "24px", "@media (pointer: coarse)": "36px" },
    display: "grid",
    placeItems: "center",
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    touchAction: "none",
    pointerEvents: "auto",
  },
  handleDot: {
    width: { default: "9px", "@media (pointer: coarse)": "13px" },
    height: { default: "9px", "@media (pointer: coarse)": "13px" },
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: colors.accent,
    backgroundColor: colors.text,
    boxShadow: "0 0 0 1px #fff, 0 1px 4px #000b",
    borderRadius: "2px",
    pointerEvents: "none",
  },
  image: { width: "100%", height: "100%", objectFit: "contain", pointerEvents: "none" },
  text: {
    width: "100%",
    height: "100%",
    padding: "0.8em",
    backgroundColor: colors.surfaceRaised,
    whiteSpace: "pre-wrap",
    overflow: "hidden",
    boxShadow: "0 4px 24px #0002",
    borderRadius: radii.md,
  },
  toolbar: {
    position: "absolute",
    zIndex: 2,
    top: space.x3,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    gap: space.x2,
    padding: space.x2,
    maxWidth: { default: "calc(100% - 816px)", "@media (max-width: 1100px)": "calc(100% - 16px)" },
    width: "max-content",
    flexWrap: "wrap",
    justifyContent: "center",
    overscrollBehavior: "contain",
    whiteSpace: "nowrap",
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
  },
  control: {
    flexShrink: 0,
    minWidth: { default: "40px", "@media (pointer: coarse)": "44px" },
    minHeight: { default: "40px", "@media (pointer: coarse)": "44px" },
    padding: "8px",
    borderWidth: 0,
    borderRadius: radii.md,
    color: colors.text,
    backgroundColor: { default: "transparent", ":hover": colors.surfaceRaised },
    cursor: "pointer",
    touchAction: "manipulation",
    ":disabled": { opacity: 0.45, cursor: "default" },
  },
  activeControl: { backgroundColor: colors.surfaceRaised, outline: `1px solid ${colors.accent}` },
  zoomValue: { minWidth: "58px", fontVariantNumeric: "tabular-nums", fontSize: "13px" },
  navigation: {
    position: "absolute",
    zIndex: 4,
    bottom: space.x3,
    left: space.x3,
    display: "flex",
    padding: space.x1,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
  },
  objectActions: {
    position: "absolute",
    zIndex: 2,
    top: "72px",
    left: "50%",
    transform: "translateX(-50%)",
    maxWidth: "calc(100% - 16px)",
    display: "flex",
    gap: space.x2,
    padding: space.x2,
    overflowX: "auto",
    whiteSpace: "nowrap",
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
  },
  sharing: {
    position: "absolute",
    zIndex: 4,
    bottom: { default: space.x3, "@media (max-width: 850px)": "68px" },
    right: space.x3,
    maxWidth: { default: "calc(100% - 250px)", "@media (max-width: 850px)": "calc(100% - 24px)" },
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: space.x2,
    padding: space.x2,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
  },
  help: {
    position: "absolute",
    left: space.x3,
    bottom: "64px",
    margin: 0,
    fontSize: "11px",
    color: colors.textMuted,
    pointerEvents: "none",
    display: { default: "block", "@media (max-width: 850px)": "none" },
  },
  hint: {
    position: "absolute",
    top: "42%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    textAlign: "center",
    pointerEvents: "none",
    backgroundColor: colors.surface,
    padding: space.x5,
    borderRadius: radii.lg,
    width: "min(360px, 80%)",
  },
  panel: {
    position: "absolute",
    zIndex: 3,
    top: space.x3,
    bottom: "100px",
    width: "min(380px, calc(50% - 16px))",
    padding: space.x3,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    "@media (max-width: 700px)": { width: "calc(100% - 16px)", bottom: "150px" },
  },
  left: { left: space.x3 },
  right: { right: space.x3 },
  hidden: { display: "none" },
  panelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexShrink: 0,
    gap: space.x2,
    paddingBottom: space.x2,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    marginBottom: space.x2,
    fontSize: "13px",
    fontWeight: 600,
  },
  panelTab: {
    position: "absolute",
    top: { default: space.x3, "@media (max-width: 700px)": "72px" },
    zIndex: 3,
    display: "flex",
    alignItems: "center",
    gap: space.x2,
    padding: "10px 12px",
    minHeight: "44px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.borderStrong,
    backgroundColor: { default: colors.surface, ":hover": colors.surfaceRaised },
    color: colors.text,
    boxShadow: "0 4px 16px #0003",
    cursor: "pointer",
  },
  leftTab: { left: 0, borderRadius: "0 8px 8px 0" },
  rightTab: { right: 0, borderRadius: "8px 0 0 8px" },
  unread: {
    minWidth: "20px",
    padding: "2px 5px",
    borderRadius: radii.full,
    backgroundColor: colors.accent,
    color: colors.accentText,
    fontSize: "11px",
    fontWeight: 700,
    textAlign: "center",
    fontVariantNumeric: "tabular-nums",
  },
  tools: { flex: 1, minHeight: 0, maxHeight: "none", overflowY: "auto" },
  chat: { flex: 1, height: "auto", minHeight: 0 },
  remoteCursor: {
    position: "absolute",
    left: 0,
    top: 0,
    pointerEvents: "none",
    zIndex: 1,
  },
  cursorName: {
    display: "block",
    marginLeft: "16px",
    marginTop: "-5px",
    padding: "3px 7px",
    borderRadius: "4px",
    backgroundColor: "#222",
    color: "#fff",
    borderLeftWidth: "3px",
    borderLeftStyle: "solid",
    maxWidth: "160px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "12px",
    lineHeight: "18px",
  },
  status: { fontSize: "12px", color: colors.textMuted },
});
