import * as stylex from "@stylexjs/stylex";
import { colors, radii, space } from "../theme/tokens.stylex";

export const boardStyles = stylex.create({
  world: { height: "100dvh", minHeight: 0, overflow: "hidden" },
  content: { flex: 1, minHeight: 0, display: "flex", flexDirection: "column" },
  header: { padding: space.x3, marginBottom: 0, backgroundColor: colors.surface },
  stage: { position: "relative", flex: 1, minHeight: 0, overflow: "hidden", isolation: "isolate" },
  board: { position: "absolute", inset: 0, backgroundColor: colors.canvas },
  viewport: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    touchAction: "none",
    outlineOffset: "-3px",
    overscrollBehavior: "contain",
  },
  background: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    pointerEvents: "none",
    opacity: 0.75,
  },
  scene: { position: "absolute", left: 0, top: 0, transformOrigin: "0 0", willChange: "transform" },
  element: {
    position: "absolute",
    left: 0,
    top: 0,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: colors.text,
    textAlign: "left",
    touchAction: "none",
    userSelect: "none",
    borderRadius: radii.md,
  },
  textEditor: {
    zIndex: 1,
    outline: `2px solid ${colors.accent}`,
    outlineOffset: "2px",
    resize: "none",
    userSelect: "text",
    touchAction: "auto",
    overflow: "auto",
    lineHeight: "inherit",
    fontFamily: "inherit",
  },
  selection: {
    position: "absolute",
    outline: `2px solid ${colors.accent}`,
    pointerEvents: "none",
  },
  resizeHandle: {
    position: "absolute",
    transform: "translate(-50%, -50%)",
    width: { default: "24px", "@media (pointer: coarse)": "36px" },
    height: { default: "24px", "@media (pointer: coarse)": "36px" },
    display: "grid",
    placeItems: "center",
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    touchAction: "none",
    pointerEvents: "auto",
  },
  handleDot: {
    width: { default: "9px", "@media (pointer: coarse)": "13px" },
    height: { default: "9px", "@media (pointer: coarse)": "13px" },
    border: `2px solid ${colors.accent}`,
    backgroundColor: colors.surface,
    borderRadius: "2px",
    pointerEvents: "none",
  },
  image: { width: "100%", height: "100%", objectFit: "contain", pointerEvents: "none" },
  text: {
    width: "100%",
    height: "100%",
    padding: space.x5,
    backgroundColor: colors.surfaceRaised,
    whiteSpace: "pre-wrap",
    overflow: "hidden",
    boxShadow: "0 4px 24px #0002",
    borderRadius: radii.md,
    fontSize: "20px",
  },
  toolbar: {
    position: "absolute",
    zIndex: 2,
    top: space.x3,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    gap: space.x2,
    padding: space.x2,
    maxWidth: "calc(100% - 16px)",
    width: "max-content",
    overflowX: "auto",
    overscrollBehavior: "contain",
    whiteSpace: "nowrap",
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
  },
  control: {
    flexShrink: 0,
    minWidth: { default: "40px", "@media (pointer: coarse)": "44px" },
    minHeight: { default: "40px", "@media (pointer: coarse)": "44px" },
    padding: "8px",
    borderWidth: 0,
    borderRadius: radii.md,
    color: colors.text,
    backgroundColor: { default: "transparent", ":hover": colors.surfaceRaised },
    cursor: "pointer",
    touchAction: "manipulation",
    ":disabled": { opacity: 0.45, cursor: "default" },
  },
  activeControl: { backgroundColor: colors.surfaceRaised, outline: `1px solid ${colors.accent}` },
  zoomValue: { minWidth: "58px", fontVariantNumeric: "tabular-nums", fontSize: "13px" },
  navigation: {
    position: "absolute",
    zIndex: 4,
    bottom: space.x3,
    left: space.x3,
    display: "flex",
    padding: space.x1,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
  },
  objectActions: {
    position: "absolute",
    zIndex: 2,
    top: "72px",
    left: "50%",
    transform: "translateX(-50%)",
    maxWidth: "calc(100% - 16px)",
    display: "flex",
    gap: space.x2,
    padding: space.x2,
    overflowX: "auto",
    whiteSpace: "nowrap",
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
  },
  sharing: {
    position: "absolute",
    zIndex: 4,
    bottom: { default: space.x3, "@media (max-width: 850px)": "68px" },
    right: space.x3,
    maxWidth: { default: "calc(100% - 250px)", "@media (max-width: 850px)": "calc(100% - 24px)" },
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: space.x2,
    padding: space.x2,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
  },
  help: {
    position: "absolute",
    left: space.x3,
    bottom: "64px",
    margin: 0,
    fontSize: "11px",
    color: colors.textMuted,
    pointerEvents: "none",
    display: { default: "block", "@media (max-width: 850px)": "none" },
  },
  hint: {
    position: "absolute",
    top: "42%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    textAlign: "center",
    pointerEvents: "none",
    backgroundColor: colors.surface,
    padding: space.x5,
    borderRadius: radii.lg,
    width: "min(360px, 80%)",
  },
  panel: {
    position: "absolute",
    zIndex: 3,
    top: space.x3,
    bottom: "100px",
    width: "min(380px, calc(50% - 16px))",
    padding: space.x3,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    boxShadow: "0 4px 24px #0003",
    overflowY: "auto",
    "@media (max-width: 700px)": { width: "calc(100% - 16px)", bottom: "150px" },
  },
  left: { left: space.x3 },
  right: { right: space.x3 },
  hidden: { display: "none" },
  tools: { maxHeight: "none", overflowY: "visible" },
  chat: { height: "100%", minHeight: 0 },
  status: { fontSize: "12px", color: colors.textMuted },
});
