import * as stylex from "@stylexjs/stylex";
import {
  colors,
  fonts,
  fontSize,
  fontWeight,
  letterSpacing,
  lineHeight,
  radii,
  shadows,
  space,
  zIndex,
} from "../theme/tokens.stylex";

export const styles = stylex.create({
  // -------------------------------------------------------------------------
  // Layout
  // -------------------------------------------------------------------------
  app: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  topbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.x4,
    paddingInline: space.x5,
    height: "52px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
    position: "sticky",
    top: 0,
    zIndex: zIndex.dropdown,
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: space.x3,
    fontWeight: fontWeight.bold,
    letterSpacing: letterSpacing.tight,
    fontSize: fontSize.subheading,
  },
  brandMark: {
    width: "18px",
    height: "18px",
    borderRadius: radii.sm,
    backgroundColor: colors.primary,
    display: "inline-block",
  },
  topbarActions: {
    display: "flex",
    alignItems: "center",
    gap: space.x3,
  },
  container: {
    width: "100%",
    maxWidth: "1120px",
    marginInline: "auto",
    paddingInline: space.x5,
    paddingBlock: space.x6,
  },
  containerNarrow: {
    width: "100%",
    maxWidth: "460px",
    marginInline: "auto",
    paddingInline: space.x5,
    paddingBlock: space.x8,
  },
  center: {
    minHeight: "70vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: space.x5,
  },
  row: { display: "flex", alignItems: "center", gap: space.x3 },
  rowWrap: { display: "flex", alignItems: "center", gap: space.x3, flexWrap: "wrap" },
  col: { display: "flex", flexDirection: "column", gap: space.x3 },
  spacer: { flex: 1 },

  // -------------------------------------------------------------------------
  // Surfaces
  // -------------------------------------------------------------------------
  window: {
    backgroundColor: colors.surface,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.lg,
    overflow: "hidden",
  },
  windowTitle: {
    height: "38px",
    display: "flex",
    alignItems: "center",
    gap: space.x3,
    paddingInline: space.x4,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    backgroundColor: colors.surfaceRaised,
    fontFamily: fonts.mono,
    fontSize: fontSize.micro,
    letterSpacing: letterSpacing.wide,
    textTransform: "uppercase",
    color: colors.textMuted,
  },
  windowBody: {
    padding: space.x5,
  },
  card: {
    backgroundColor: colors.surface,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: space.x5,
    display: "flex",
    flexDirection: "column",
    gap: space.x2,
    transitionProperty: "background-color, border-color",
    transitionDuration: "0.15s",
  },
  cardInteractive: {
    cursor: "pointer",
    ":hover": { backgroundColor: colors.surfaceHover, borderColor: colors.borderStrong },
  },
  panel: {
    backgroundColor: colors.surfaceRaised,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: space.x4,
  },
  inset: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    padding: space.x4,
  },

  // -------------------------------------------------------------------------
  // Text
  // -------------------------------------------------------------------------
  h1: {
    fontSize: fontSize.display,
    fontWeight: fontWeight.extrabold,
    letterSpacing: letterSpacing.tight,
    lineHeight: lineHeight.tight,
    margin: 0,
  },
  h2: {
    fontSize: fontSize.headingLg,
    fontWeight: fontWeight.bold,
    letterSpacing: letterSpacing.tight,
    margin: 0,
  },
  h3: {
    fontSize: fontSize.heading,
    fontWeight: fontWeight.semibold,
    letterSpacing: letterSpacing.tight,
    margin: 0,
  },
  h4: {
    fontSize: fontSize.subheading,
    fontWeight: fontWeight.semibold,
    margin: 0,
  },
  body: { fontSize: fontSize.body, lineHeight: lineHeight.normal, margin: 0 },
  muted: { color: colors.textMuted, fontSize: fontSize.caption, margin: 0 },
  faint: { color: colors.textFaint, fontSize: fontSize.micro, margin: 0 },
  mono: { fontFamily: fonts.mono, fontSize: fontSize.caption },
  eyebrow: {
    fontFamily: fonts.mono,
    fontSize: fontSize.micro,
    letterSpacing: letterSpacing.wide,
    textTransform: "uppercase",
    color: colors.textFaint,
  },
  link: {
    color: colors.accent,
    textDecorationLine: "none",
    cursor: "pointer",
    ":hover": { textDecorationLine: "underline" },
  },

  // -------------------------------------------------------------------------
  // Controls
  // -------------------------------------------------------------------------
  button: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: space.x2,
    paddingInline: space.x4,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    backgroundColor: colors.surfaceMuted,
    color: colors.text,
    fontSize: fontSize.caption,
    fontWeight: fontWeight.medium,
    cursor: "pointer",
    textDecorationLine: "none",
    transitionProperty: "background-color, border-color, color, opacity",
    transitionDuration: "0.15s",
    ":disabled": { opacity: 0.5, cursor: "not-allowed" },
  },
  buttonPrimary: {
    backgroundColor: colors.primary,
    color: colors.primaryText,
    ":hover": { backgroundColor: colors.primaryHover },
  },
  buttonAccent: {
    backgroundColor: colors.accent,
    color: colors.accentText,
  },
  buttonGhost: {
    backgroundColor: "transparent",
    borderColor: colors.border,
    color: colors.textMuted,
    ":hover": { backgroundColor: colors.surfaceHover, color: colors.text },
  },
  buttonDanger: {
    backgroundColor: "transparent",
    borderColor: colors.danger,
    color: colors.danger,
    ":hover": { backgroundColor: colors.dangerMuted },
  },
  buttonSmall: {
    paddingInline: space.x3,
    paddingBlock: space.x1,
    fontSize: fontSize.micro,
  },
  input: {
    width: "100%",
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: fontSize.caption,
    outline: "none",
    ":focus": { borderColor: colors.accent },
    "::placeholder": { color: colors.textFaint },
  },
  textarea: {
    width: "100%",
    minHeight: "240px",
    paddingInline: space.x3,
    paddingBlock: space.x3,
    borderRadius: radii.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.relaxed,
    fontFamily: fonts.mono,
    resize: "vertical",
    outline: "none",
    ":focus": { borderColor: colors.accent },
  },
  select: {
    paddingInline: space.x2,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: fontSize.caption,
    outline: "none",
  },
  field: { display: "flex", flexDirection: "column", gap: space.x1 },
  label: {
    fontSize: fontSize.micro,
    fontWeight: fontWeight.medium,
    color: colors.textMuted,
    letterSpacing: letterSpacing.wide,
    textTransform: "uppercase",
  },
  checkboxRow: { display: "flex", alignItems: "center", gap: space.x2, fontSize: fontSize.caption },

  // -------------------------------------------------------------------------
  // Badges / tags
  // -------------------------------------------------------------------------
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.x1,
    paddingInline: space.x3,
    paddingBlock: "1px",
    borderRadius: radii.full,
    fontSize: fontSize.micro,
    fontWeight: fontWeight.medium,
    backgroundColor: colors.surfaceMuted,
    color: colors.textMuted,
  },
  badgeAccent: { backgroundColor: colors.accentMuted, color: colors.accent },
  badgeSuccess: { backgroundColor: colors.successMuted, color: colors.success },
  badgeTag: { backgroundColor: colors.dangerMuted, color: colors.danger },
  badgeDm: { backgroundColor: colors.dangerMuted, color: colors.danger },
  badgePrivate: { backgroundColor: colors.accentMuted, color: colors.accent },
  badgePlain: { backgroundColor: colors.surfaceMuted, color: colors.textMuted },

  // -------------------------------------------------------------------------
  // Tabs / nav
  // -------------------------------------------------------------------------
  tabBar: {
    display: "flex",
    gap: space.x1,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  tab: {
    paddingInline: space.x4,
    paddingBlock: space.x3,
    fontSize: fontSize.caption,
    color: colors.textMuted,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderBottomWidth: "2px",
    borderBottomStyle: "solid",
    borderBottomColor: "transparent",
    cursor: "pointer",
    ":hover": { color: colors.text },
  },
  tabActive: {
    color: colors.accent,
    borderBottomColor: colors.accent,
    fontWeight: fontWeight.semibold,
  },

  // -------------------------------------------------------------------------
  // Auth
  // -------------------------------------------------------------------------
  authWindow: {
    width: "100%",
    backgroundColor: colors.surface,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.lg,
    padding: space.x6,
    display: "flex",
    flexDirection: "column",
    gap: space.x4,
  },
  authLogo: {
    display: "flex",
    alignItems: "center",
    gap: space.x3,
    fontSize: fontSize.headingLg,
    fontWeight: fontWeight.extrabold,
    letterSpacing: letterSpacing.tight,
  },

  // -------------------------------------------------------------------------
  // World shell
  // -------------------------------------------------------------------------
  worldShell: {
    display: "grid",
    gridTemplateColumns: "260px 1fr",
    gap: space.x5,
    alignItems: "start",
    "@media (max-width: 860px)": { gridTemplateColumns: "1fr" },
  },
  sidebar: {
    display: "flex",
    flexDirection: "column",
    gap: space.x4,
    position: "sticky",
    top: "68px",
    "@media (max-width: 860px)": { position: "static" },
  },
  navList: { display: "flex", flexDirection: "column", gap: space.x1 },
  navItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.x2,
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    fontSize: fontSize.caption,
    color: colors.textMuted,
    backgroundColor: "transparent",
    borderWidth: 0,
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
    ":hover": { backgroundColor: colors.surfaceHover, color: colors.text },
  },
  navItemActive: {
    backgroundColor: colors.accentMuted,
    color: colors.accent,
    fontWeight: fontWeight.semibold,
  },
  presenceDot: {
    width: "8px",
    height: "8px",
    borderRadius: radii.full,
    backgroundColor: colors.success,
    display: "inline-block",
  },
  presenceDotOffline: { backgroundColor: colors.textFaint },

  // -------------------------------------------------------------------------
  // Chat
  // -------------------------------------------------------------------------
  chatLayout: {
    display: "grid",
    gridTemplateRows: "1fr auto",
    gap: space.x4,
    height: "calc(100vh - 180px)",
    minHeight: "420px",
  },
  messageList: {
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: space.x3,
    paddingRight: space.x2,
  },
  message: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: space.x4,
    backgroundColor: colors.surface,
    display: "flex",
    flexDirection: "column",
    gap: space.x2,
  },
  messageOoc: { backgroundColor: colors.surfaceMuted, borderColor: colors.border },
  messageSystem: { backgroundColor: colors.surfaceMuted, borderStyle: "dashed" },
  messageMeta: {
    display: "flex",
    alignItems: "center",
    gap: space.x2,
    fontSize: fontSize.micro,
    color: colors.textFaint,
  },
  messageAuthor: { fontWeight: fontWeight.semibold, color: colors.textMuted },
  messageBody: {
    fontSize: fontSize.caption,
    lineHeight: lineHeight.relaxed,
    whiteSpace: "pre-wrap",
  },
  rollResult: {
    display: "flex",
    alignItems: "center",
    gap: space.x4,
    flexWrap: "wrap",
  },
  rollTotal: {
    fontFamily: fonts.mono,
    fontSize: fontSize.headingLg,
    fontWeight: fontWeight.bold,
    color: colors.accent,
  },
  die: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "24px",
    height: "24px",
    paddingInline: space.x1,
    borderRadius: radii.sm,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    fontFamily: fonts.mono,
    fontSize: fontSize.micro,
    backgroundColor: colors.surfaceMuted,
  },
  composer: {
    display: "flex",
    flexDirection: "column",
    gap: space.x2,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    paddingTop: space.x3,
  },
  composerRow: { display: "flex", gap: space.x2, alignItems: "flex-end" },
  composerInput: { flex: 1, resize: "none", minHeight: "44px", maxHeight: "160px" },

  // -------------------------------------------------------------------------
  // Sheet
  // -------------------------------------------------------------------------
  sheetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: space.x3,
  },
  statBox: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: space.x3,
    display: "flex",
    flexDirection: "column",
    gap: space.x1,
    backgroundColor: colors.surfaceRaised,
  },
  statValue: {
    fontFamily: fonts.mono,
    fontSize: fontSize.heading,
    fontWeight: fontWeight.bold,
    color: colors.text,
  },
  ticker: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: space.x3,
    display: "flex",
    flexDirection: "column",
    gap: space.x2,
  },
  tickerBar: {
    height: "8px",
    borderRadius: radii.full,
    backgroundColor: colors.surfaceMuted,
    overflow: "hidden",
  },
  tickerFill: {
    height: "100%",
    backgroundColor: colors.success,
    transitionProperty: "width",
    transitionDuration: "0.15s",
  },
  tickerControls: { display: "flex", alignItems: "center", gap: space.x2 },
  rollButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.x3,
    width: "100%",
    paddingInline: space.x4,
    paddingBlock: space.x3,
    borderRadius: radii.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    cursor: "pointer",
    textAlign: "left",
    ":hover": { borderColor: colors.accent, backgroundColor: colors.surfaceHover },
  },
  fieldValue: {
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceMuted,
    fontSize: fontSize.caption,
    minHeight: "34px",
  },

  // -------------------------------------------------------------------------
  // Notes
  // -------------------------------------------------------------------------
  notesLayout: {
    display: "grid",
    gridTemplateColumns: "220px 1fr",
    gap: space.x4,
    "@media (max-width: 720px)": { gridTemplateColumns: "1fr" },
  },
  noteItem: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    backgroundColor: "transparent",
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
    color: colors.textMuted,
    ":hover": { backgroundColor: colors.surfaceHover },
  },
  noteItemActive: {
    backgroundColor: colors.accentMuted,
    color: colors.accent,
    borderColor: colors.accent,
  },

  // -------------------------------------------------------------------------
  // Builder
  // -------------------------------------------------------------------------
  builderSection: {
    display: "flex",
    flexDirection: "column",
    gap: space.x3,
    padding: space.x4,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceRaised,
  },
  builderRow: {
    display: "grid",
    gap: space.x2,
    alignItems: "center",
    gridTemplateColumns: "1.4fr 1fr 0.9fr 1fr auto",
    "@media (max-width: 720px)": { gridTemplateColumns: "1fr 1fr" },
  },
  builderRowRoll: {
    display: "grid",
    gap: space.x2,
    alignItems: "center",
    gridTemplateColumns: "1.4fr 1.6fr 0.8fr auto",
    "@media (max-width: 720px)": { gridTemplateColumns: "1fr 1fr" },
  },
  modifier: {
    display: "grid",
    gap: space.x2,
    alignItems: "center",
    gridTemplateColumns: "1fr 1fr auto auto",
    padding: space.x2,
    borderRadius: radii.sm,
    backgroundColor: colors.surfaceMuted,
  },
  diceGroup: {
    display: "grid",
    gap: space.x2,
    alignItems: "center",
    gridTemplateColumns: "1fr 1fr auto",
  },

  // -------------------------------------------------------------------------
  // Misc
  // -------------------------------------------------------------------------
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: colors.overlay,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: space.x5,
    zIndex: zIndex.modal,
  },
  modal: {
    width: "100%",
    maxWidth: "520px",
    maxHeight: "85vh",
    overflowY: "auto",
    backgroundColor: colors.surface,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.xl,
    boxShadow: shadows.modal,
    padding: space.x5,
    display: "flex",
    flexDirection: "column",
    gap: space.x4,
  },
  empty: {
    padding: space.x8,
    textAlign: "center",
    color: colors.textFaint,
    fontSize: fontSize.caption,
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: colors.border,
    borderRadius: radii.md,
  },
  errorBanner: {
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    backgroundColor: colors.dangerMuted,
    color: colors.danger,
    fontSize: fontSize.caption,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.danger,
  },
  successBanner: {
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    backgroundColor: colors.successMuted,
    color: colors.success,
    fontSize: fontSize.caption,
  },
  divider: {
    height: "1px",
    backgroundColor: colors.border,
    borderWidth: 0,
    marginBlock: space.x2,
  },
  avatar: {
    width: "28px",
    height: "28px",
    borderRadius: radii.full,
    backgroundColor: colors.accentMuted,
    color: colors.accent,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: fontSize.micro,
    fontWeight: fontWeight.bold,
    flexShrink: 0,
  },
  scrollArea: { overflowY: "auto" },
  transition: {
    transitionProperty: "background-color, color, border-color, opacity",
    transitionDuration: "0.15s",
    transitionTimingFunction: "ease",
  },
  statusPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.x1,
    fontSize: fontSize.micro,
    color: colors.textFaint,
    fontFamily: fonts.mono,
  },
  grow: { flex: 1, minWidth: 0 },
  minWidth0: { minWidth: 0 },
  hidden: { display: "none" },
});
