import * as stylex from "@stylexjs/stylex";
import {
  colors,
  fonts,
  fontSize,
  fontWeight,
  lineHeight,
  radii,
  skin,
  space,
  zIndex,
} from "../theme/tokens.stylex";

export const styles = stylex.create({
  // -------------------------------------------------------------------------
  // Layout
  // -------------------------------------------------------------------------
  app: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  topbar: {
    backgroundImage: skin.paper,
    backgroundSize: skin.paperSize,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.x4,
    paddingInline: space.x5,
    height: "52px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
    position: "sticky",
    top: 0,
    zIndex: zIndex.dropdown,
  },
  brand: {
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    display: "flex",
    alignItems: "center",
    gap: space.x3,
    fontSize: fontSize.subheading,
  },
  brandMark: {
    width: "18px",
    height: "18px",
    borderRadius: radii.sm,
    backgroundColor: colors.primary,
    display: "inline-block",
  },
  iconButton: {
    borderRadius: skin.controlRadius,
    boxShadow: skin.controlShadow,
    fontFamily: fonts.body,
    display: "inline-grid",
    placeItems: "center",
    minWidth: "32px",
    height: "32px",
    paddingInline: space.x2,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    backgroundColor: { default: "transparent", ":hover": colors.surfaceHover },
    color: colors.textMuted,
    fontSize: "16px",
    lineHeight: 1,
    cursor: "pointer",
    ":focus-visible": { outline: `2px solid ${colors.accent}`, outlineOffset: "1px" },
  },
  menu: { position: "relative" },
  menuPanel: {
    backgroundColor: colors.surface,
    backgroundImage: skin.paper,
    backgroundSize: skin.paperSize,
    borderWidth: skin.panelBorderWidth,
    boxShadow: skin.panelShadow,
    position: "absolute",
    right: 0,
    top: "calc(100% + 6px)",
    zIndex: zIndex.dropdown,
    minWidth: "220px",
    display: "flex",
    flexDirection: "column",
    padding: space.x1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.lg,
  },
  menuItem: {
    borderRadius: skin.controlRadius,
    boxShadow: skin.controlShadow,
    fontFamily: fonts.body,
    display: "flex",
    alignItems: "center",
    gap: space.x2,
    width: "100%",
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderWidth: 0,
    backgroundColor: { default: "transparent", ":hover": colors.surfaceHover },
    color: colors.text,
    fontSize: fontSize.caption,
    textAlign: "left",
    cursor: "pointer",
  },
  menuCheck: { width: "14px", color: colors.text, fontWeight: fontWeight.bold },
  menuDivider: { height: skin.ruleHeight, marginBlock: space.x1, backgroundImage: skin.rule },
  topbarActions: {
    display: "flex",
    alignItems: "center",
    gap: space.x3,
  },
  container: {
    width: "100%",
    paddingInline: space.x5,
    paddingBlock: space.x5,
  },
  settingsPage: {
    width: "100%",
    maxWidth: "1100px",
    marginInline: "auto",
    paddingInline: space.x5,
    paddingBlock: space.x5,
    display: "flex",
    flexDirection: "column",
    gap: space.x4,
  },
  containerNarrow: {
    width: "100%",
    maxWidth: "460px",
    marginInline: "auto",
    paddingInline: space.x5,
    paddingBlock: space.x8,
  },
  center: {
    minHeight: "70vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: space.x5,
  },
  row: { display: "flex", alignItems: "center", gap: space.x3 },
  rowWrap: { display: "flex", alignItems: "center", gap: space.x3, flexWrap: "wrap" },
  col: { display: "flex", flexDirection: "column", gap: space.x3 },
  spacer: { flex: 1 },

  // -------------------------------------------------------------------------
  // Surfaces
  // -------------------------------------------------------------------------
  window: {
    backgroundColor: colors.surface,
    backgroundImage: skin.paper,
    backgroundSize: skin.paperSize,
    borderWidth: skin.panelBorderWidth,
    boxShadow: skin.panelShadow,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.lg,
    overflow: "hidden",
  },
  windowTitle: {
    backgroundImage: skin.band,
    backgroundSize: skin.bandSize,
    "::before": { content: skin.ornament, marginRight: space.x2, color: colors.textMuted },
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    height: "38px",
    display: "flex",
    alignItems: "center",
    gap: space.x3,
    paddingInline: space.x4,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    backgroundColor: colors.surfaceRaised,
    fontSize: fontSize.micro,
    color: colors.textMuted,
  },
  windowBody: {
    padding: space.x5,
  },
  card: {
    padding: space.x4,
    color: colors.text,
    textAlign: "left",
    backgroundColor: colors.surface,
    backgroundImage: skin.paper,
    backgroundSize: skin.paperSize,
    borderWidth: skin.panelBorderWidth,
    boxShadow: skin.panelShadow,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    display: "flex",
    flexDirection: "column",
    gap: space.x2,
    transitionProperty: "background-color, border-color",
    transitionDuration: "0.15s",
  },
  cardInteractive: {
    cursor: "pointer",
    ":hover": { backgroundColor: colors.surfaceHover, borderColor: colors.borderStrong },
  },
  panel: {
    padding: space.x3,
    backgroundColor: colors.surface,
    backgroundImage: skin.paper,
    backgroundSize: skin.paperSize,
    borderWidth: skin.panelBorderWidth,
    boxShadow: skin.panelShadow,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
  },
  inset: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    padding: space.x4,
  },

  // -------------------------------------------------------------------------
  // Text
  // -------------------------------------------------------------------------
  h1: {
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    fontSize: fontSize.display,
    lineHeight: lineHeight.tight,
    margin: 0,
  },
  h2: {
    "::before": { content: skin.ornament, marginRight: space.x2, color: colors.textMuted },
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    fontSize: fontSize.headingLg,
    margin: 0,
  },
  h3: {
    "::before": { content: skin.ornament, marginRight: space.x2, color: colors.textMuted },
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    fontSize: fontSize.heading,
    margin: 0,
  },
  h4: {
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    fontSize: fontSize.subheading,
    margin: 0,
  },
  body: { fontSize: fontSize.body, lineHeight: lineHeight.normal, margin: 0 },
  muted: { color: colors.textMuted, fontSize: fontSize.caption, margin: 0 },
  faint: { color: colors.textMuted, fontSize: fontSize.micro, margin: 0 },
  mono: { fontFamily: fonts.mono, fontSize: fontSize.caption },
  eyebrow: {
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    fontSize: fontSize.micro,
    color: colors.textMuted,
  },
  link: {
    color: colors.text,
    textDecorationLine: "underline",
    textDecorationColor: colors.accent,
    cursor: "pointer",
    ":hover": { textDecorationLine: "underline" },
  },

  // -------------------------------------------------------------------------
  // Controls
  // -------------------------------------------------------------------------
  button: {
    borderColor: colors.border,
    borderRadius: skin.controlRadius,
    boxShadow: skin.controlShadow,
    fontFamily: fonts.body,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: space.x2,
    paddingInline: space.x4,
    paddingBlock: space.x2,
    borderWidth: "1px",
    borderStyle: "solid",
    backgroundColor: colors.surfaceMuted,
    color: colors.text,
    fontSize: fontSize.caption,
    fontWeight: fontWeight.medium,
    cursor: "pointer",
    textDecorationLine: "none",
    transitionProperty: "background-color, border-color, color, opacity",
    transitionDuration: "0.15s",
    ":disabled": { opacity: 0.5, cursor: "not-allowed" },
  },
  buttonPrimary: {
    backgroundColor: colors.primary,
    color: colors.primaryText,
    ":hover": { backgroundColor: colors.primaryHover },
  },
  buttonAccent: {
    backgroundColor: colors.accent,
    color: colors.accentText,
  },
  buttonGhost: {
    backgroundColor: "transparent",
    borderColor: colors.border,
    color: colors.textMuted,
    ":hover": { backgroundColor: colors.surfaceHover, color: colors.text },
  },
  buttonDanger: {
    color: colors.text,
    backgroundColor: "transparent",
    borderColor: colors.danger,
    ":hover": { backgroundColor: colors.dangerMuted },
  },
  buttonSmall: {
    paddingInline: space.x3,
    paddingBlock: space.x1,
    fontSize: fontSize.micro,
  },
  input: {
    borderRadius: skin.controlRadius,
    boxShadow: skin.controlShadow,
    fontFamily: fonts.body,
    width: "100%",
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: fontSize.caption,
    outline: "none",
    ":focus": { borderColor: colors.accent },
    "::placeholder": { color: colors.textMuted },
  },
  textarea: {
    fontSize: fontSize.body,
    borderRadius: skin.controlRadius,
    boxShadow: skin.controlShadow,
    fontFamily: fonts.body,
    width: "100%",
    minHeight: "240px",
    paddingInline: space.x3,
    paddingBlock: space.x3,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    lineHeight: lineHeight.relaxed,
    resize: "vertical",
    outline: "none",
    ":focus": { borderColor: colors.accent },
  },
  select: {
    borderRadius: skin.controlRadius,
    boxShadow: skin.controlShadow,
    fontFamily: fonts.body,
    paddingInline: space.x2,
    paddingBlock: space.x2,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: fontSize.caption,
    outline: "none",
  },
  field: { display: "flex", flexDirection: "column", gap: space.x1 },
  label: {
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    fontSize: fontSize.micro,
    color: colors.textMuted,
  },
  checkboxRow: { display: "flex", alignItems: "center", gap: space.x2, fontSize: fontSize.caption },

  // -------------------------------------------------------------------------
  // Badges / tags
  // -------------------------------------------------------------------------
  badge: {
    borderRadius: radii.sm,
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    paddingInline: space.x2,
    display: "inline-flex",
    alignItems: "center",
    gap: space.x1,
    paddingBlock: "1px",
    fontSize: fontSize.micro,
    backgroundColor: colors.surfaceMuted,
    color: colors.textMuted,
  },
  badgeAccent: { backgroundColor: colors.accentMuted, color: colors.text },
  badgeSuccess: { backgroundColor: colors.successMuted, color: colors.text },
  badgeTag: { backgroundColor: colors.dangerMuted, color: colors.text },
  badgeDm: { backgroundColor: colors.dangerMuted, color: colors.text },
  badgePrivate: { backgroundColor: colors.accentMuted, color: colors.text },
  badgePlain: { backgroundColor: colors.surfaceMuted, color: colors.textMuted },

  // -------------------------------------------------------------------------
  // Tabs / nav
  // -------------------------------------------------------------------------
  tabBar: {
    display: "flex",
    gap: space.x1,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  tab: {
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    paddingInline: space.x4,
    paddingBlock: space.x3,
    fontSize: fontSize.caption,
    color: colors.textMuted,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderBottomWidth: "2px",
    borderBottomStyle: "solid",
    borderBottomColor: "transparent",
    cursor: "pointer",
    ":hover": { color: colors.text },
  },
  tabActive: {
    color: colors.text,
    fontWeight: skin.headWeight,
    borderBottomColor: colors.accent,
  },

  // -------------------------------------------------------------------------
  // Auth
  // -------------------------------------------------------------------------
  authWindow: {
    backgroundColor: colors.surface,
    backgroundImage: skin.paper,
    backgroundSize: skin.paperSize,
    borderWidth: skin.panelBorderWidth,
    boxShadow: skin.panelShadow,
    width: "100%",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.lg,
    padding: space.x6,
    display: "flex",
    flexDirection: "column",
    gap: space.x4,
  },
  authLogo: {
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    display: "flex",
    alignItems: "center",
    gap: space.x3,
    fontSize: fontSize.headingLg,
  },

  // -------------------------------------------------------------------------
  // World shell
  // -------------------------------------------------------------------------
  worldShell: {
    display: "grid",
    gridTemplateColumns: "260px 1fr",
    gap: space.x5,
    alignItems: "start",
    "@media (max-width: 860px)": { gridTemplateColumns: "1fr" },
  },
  sidebar: {
    display: "flex",
    flexDirection: "column",
    gap: space.x4,
    position: "sticky",
    top: "68px",
    "@media (max-width: 860px)": { position: "static" },
  },
  navList: { display: "flex", flexDirection: "column", gap: space.x1 },
  navItem: {
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.x2,
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    fontSize: fontSize.caption,
    color: colors.textMuted,
    backgroundColor: "transparent",
    borderWidth: 0,
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
    ":hover": { backgroundColor: colors.surfaceHover, color: colors.text },
  },
  navItemActive: {
    color: colors.text,
    backgroundColor: colors.accentMuted,
    fontWeight: fontWeight.semibold,
  },
  presenceDot: {
    width: "8px",
    height: "8px",
    borderRadius: radii.full,
    backgroundColor: colors.success,
    display: "inline-block",
  },
  presenceDotOffline: { backgroundColor: colors.textFaint },

  // -------------------------------------------------------------------------
  // Chat
  // -------------------------------------------------------------------------
  chatLayout: {
    gap: space.x2,
    display: "grid",
    gridTemplateRows: "1fr auto",
    height: "calc(100vh - 180px)",
    minHeight: "420px",
  },
  messageList: {
    gap: space.x1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    paddingRight: space.x2,
  },
  message: {
    borderWidth: 0,
    borderBottomWidth: "1px",
    borderRadius: 0,
    padding: 0,
    paddingBlock: space.x2,
    backgroundColor: "transparent",
    gap: space.x1,
    borderStyle: "solid",
    borderColor: colors.border,
    display: "flex",
    flexDirection: "column",
  },
  messageOoc: { color: colors.textMuted },
  messageSystem: { color: colors.textMuted, textAlign: "center", fontStyle: "italic" },
  messageMeta: {
    flexWrap: "wrap",
    columnGap: space.x2,
    rowGap: 0,
    display: "flex",
    alignItems: "center",
    fontSize: fontSize.micro,
    color: colors.textMuted,
  },
  messageMetaCentered: { justifyContent: "center" },
  messageAuthor: {
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    letterSpacing: skin.headTracking,
    textTransform: skin.headTransform,
    color: colors.text,
  },
  messageRow: { display: "flex", alignItems: "flex-start", gap: space.x2 },
  messageQuiet: { fontSize: fontSize.caption, color: colors.textMuted },
  messageMark: {
    fontFamily: fonts.display,
    fontSize: fontSize.micro,
    color: colors.textMuted,
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: colors.borderStrong,
    paddingLeft: space.x1,
  },
  chatAvatar: { width: "24px", height: "24px", borderRadius: radii.sm, color: colors.text },
  numeric: { fontFamily: fonts.numeric },
  menuGroupLabel: {
    fontFamily: fonts.display,
    fontWeight: skin.headWeight,
    textTransform: skin.headTransform,
    letterSpacing: skin.headTracking,
    fontSize: fontSize.micro,
    color: colors.textMuted,
    padding: space.x2,
  },
  themeSwatch: {
    width: "16px",
    height: "16px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.borderStrong,
    flexShrink: 0,
  },
  swatchRulebook: { backgroundImage: "linear-gradient(135deg, #f1e9d6 50%, #1f1a14 50%)" },
  swatchZine: { backgroundImage: "linear-gradient(135deg, #f7f4ec 50%, #111111 50%)" },
  swatchFantasy: { backgroundImage: "linear-gradient(135deg, #16130f 50%, #e8dcc4 50%)" },
  messageBody: {
    fontFamily: fonts.body,
    fontSize: fontSize.body,
    lineHeight: lineHeight.normal,
    whiteSpace: "pre-wrap",
  },
  rollResult: {
    gap: space.x2,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
  },
  rollTotal: {
    fontFamily: fonts.numeric,
    fontSize: fontSize.micro,
    color: colors.textMuted,
  },
  die: {
    fontFamily: fonts.numeric,
    fontWeight: skin.headWeight,
    fontSize: fontSize.heading,
    borderColor: colors.borderStrong,
    borderRadius: skin.controlRadius,
    flexDirection: "row",
    alignItems: "baseline",
    gap: "2px",
    padding: space.x1,
    minWidth: "30px",
    backgroundColor: colors.surfaceRaised,
    display: "inline-flex",
    justifyContent: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    color: colors.text,
  },
  dieLabel: {
    fontSize: "10px",
    alignSelf: "flex-end",
    fontWeight: fontWeight.regular,
    color: colors.textMuted,
  },
  // One row at any panel width: the "To" picker absorbs the slack, Send stays put.
  composerControls: {
    display: "flex",
    alignItems: "center",
    gap: space.x2,
    flexWrap: "nowrap",
    minWidth: 0,
  },
  composerSelect: { flex: 1, minWidth: 0, width: "100%" },
  chatAudienceSelect: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.x2,
    fontSize: fontSize.micro,
    minWidth: 0,
    flex: 1,
  },
  chatEmpty: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: space.x2,
    padding: space.x5,
    textAlign: "center",
    fontSize: fontSize.caption,
    color: colors.textMuted,
  },
  chatAudience: {
    backgroundColor: colors.surfaceMuted,
    color: colors.text,
    borderRadius: radii.sm,
    borderLeftWidth: "2px",
    borderLeftStyle: "solid",
    borderLeftColor: colors.borderStrong,
    padding: space.x2,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: space.x3,
    fontWeight: fontWeight.semibold,
    fontSize: fontSize.caption,
  },
  chatAudienceInput: {
    borderColor: colors.borderStrong,
    boxShadow: skin.controlShadow,
  },
  composer: {
    display: "flex",
    flexDirection: "column",
    gap: space.x2,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    paddingTop: space.x3,
  },
  composerRow: { display: "flex", gap: space.x2, alignItems: "flex-end" },
  composerField: { position: "relative", display: "flex", flexDirection: "column" },
  composerInput: {
    fontSize: fontSize.body,
    flex: 1,
    resize: "none",
    minHeight: "44px",
    maxHeight: "160px",
  },

  // -------------------------------------------------------------------------
  // Sheet
  // -------------------------------------------------------------------------
  sheetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: space.x3,
  },
  statBox: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: space.x3,
    display: "flex",
    flexDirection: "column",
    gap: space.x1,
    backgroundColor: colors.surfaceRaised,
  },
  statValue: {
    fontFamily: fonts.mono,
    fontSize: fontSize.heading,
    fontWeight: fontWeight.bold,
    color: colors.text,
  },
  ticker: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: space.x3,
    display: "flex",
    flexDirection: "column",
    gap: space.x2,
  },
  tickerBar: {
    height: "8px",
    borderRadius: radii.full,
    backgroundColor: colors.surfaceMuted,
    overflow: "hidden",
  },
  tickerFill: {
    height: "100%",
    backgroundColor: colors.success,
    transitionProperty: "width",
    transitionDuration: "0.15s",
  },
  tickerControls: { display: "flex", alignItems: "center", gap: space.x2 },
  rollButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.x3,
    width: "100%",
    paddingInline: space.x4,
    paddingBlock: space.x3,
    borderRadius: radii.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    cursor: "pointer",
    textAlign: "left",
    ":hover": { borderColor: colors.accent, backgroundColor: colors.surfaceHover },
    ":disabled": { opacity: 0.45, cursor: "not-allowed", borderColor: colors.border },
  },
  fieldValue: {
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceMuted,
    fontSize: fontSize.caption,
    minHeight: "34px",
  },

  // -------------------------------------------------------------------------
  // Notes
  // -------------------------------------------------------------------------
  notesLayout: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: space.x4,
  },
  noteItem: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    backgroundColor: "transparent",
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
    color: colors.textMuted,
    ":hover": { backgroundColor: colors.surfaceHover },
  },
  noteItemActive: {
    backgroundColor: colors.accentMuted,
    color: colors.accent,
    borderColor: colors.accent,
  },
  noteReadonly: {
    whiteSpace: "pre-wrap",
    fontFamily: fonts.mono,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.relaxed,
    padding: space.x4,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceMuted,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    minHeight: "240px",
  },

  // -------------------------------------------------------------------------
  // Builder
  // -------------------------------------------------------------------------
  builderSection: {
    display: "flex",
    flexDirection: "column",
    gap: space.x3,
    padding: space.x4,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceRaised,
  },
  builderRow: {
    display: "grid",
    gap: space.x2,
    alignItems: "start",
  },
  builderHeadings: {
    display: "grid",
    gap: space.x2,
    fontSize: fontSize.micro,
    color: colors.textMuted,
    fontWeight: fontWeight.semibold,
  },
  builderFieldsGrid: { gridTemplateColumns: "minmax(0, 2fr) minmax(0, 1fr) minmax(0, 1.2fr) 36px" },
  builderStatsGrid: { gridTemplateColumns: "minmax(0, 3fr) minmax(0, 1fr) 36px" },
  builderTrackersGrid: {
    gridTemplateColumns: "minmax(0, 2fr) repeat(3, minmax(0, 0.7fr)) 36px",
  },
  builderRollsGrid: { gridTemplateColumns: "minmax(0, 3fr) minmax(0, 1fr) 36px" },
  builderLabelCell: { display: "flex", flexDirection: "column", gap: "2px", minWidth: 0 },
  builderId: { fontFamily: fonts.mono, fontSize: "11px", color: colors.textFaint },
  modifier: {
    display: "grid",
    gap: space.x2,
    alignItems: "center",
    gridTemplateColumns: "1fr 1fr auto auto",
    padding: space.x2,
    borderRadius: radii.sm,
    backgroundColor: colors.surfaceMuted,
  },
  diceGroup: {
    display: "grid",
    gap: space.x2,
    alignItems: "center",
    gridTemplateColumns: "1fr 1fr auto",
  },

  // -------------------------------------------------------------------------
  // Misc
  // -------------------------------------------------------------------------
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: colors.overlay,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: space.x5,
    zIndex: zIndex.modal,
  },
  modal: {
    backgroundColor: colors.surface,
    backgroundImage: skin.paper,
    backgroundSize: skin.paperSize,
    borderWidth: skin.panelBorderWidth,
    boxShadow: skin.panelShadow,
    width: "100%",
    maxWidth: "520px",
    maxHeight: "85vh",
    overflowY: "auto",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.xl,
    padding: space.x5,
    display: "flex",
    flexDirection: "column",
    gap: space.x4,
  },
  empty: {
    padding: space.x8,
    textAlign: "center",
    color: colors.textMuted,
    fontSize: fontSize.caption,
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: colors.border,
    borderRadius: radii.md,
  },
  errorBanner: {
    color: colors.text,
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    backgroundColor: colors.dangerMuted,
    fontSize: fontSize.caption,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.danger,
  },
  successBanner: {
    color: colors.text,
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderRadius: radii.md,
    backgroundColor: colors.successMuted,
    fontSize: fontSize.caption,
  },
  divider: {
    height: skin.ruleHeight,
    backgroundImage: skin.rule,
    backgroundColor: "transparent",
    borderWidth: 0,
    marginBlock: space.x2,
  },
  avatar: {
    width: "28px",
    height: "28px",
    borderRadius: radii.full,
    backgroundColor: colors.accentMuted,
    color: colors.accent,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: fontSize.micro,
    fontWeight: fontWeight.bold,
    flexShrink: 0,
  },
  scrollArea: { overflowY: "auto" },
  transition: {
    transitionProperty: "background-color, color, border-color, opacity",
    transitionDuration: "0.15s",
    transitionTimingFunction: "ease",
  },
  statusPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.x1,
    fontSize: fontSize.micro,
    color: colors.textMuted,
    fontFamily: fonts.mono,
  },
  grow: { flex: 1, minWidth: 0 },
  minWidth0: { minWidth: 0 },
  hidden: { display: "none" },
  srOnly: {
    position: "absolute",
    width: "1px",
    height: "1px",
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  },

  // -------------------------------------------------------------------------
  // World layout (chat left, menu right)
  // -------------------------------------------------------------------------
  worldLayout: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 480px) minmax(0, 1fr)",
    gap: space.x5,
    alignItems: "start",
    "@media (max-width: 1000px)": { gridTemplateColumns: "1fr" },
  },
  menuColumn: {
    display: "flex",
    flexDirection: "column",
    gap: space.x4,
    maxHeight: "calc(100vh - 170px)",
    overflowY: "auto",
    "@media (max-width: 1000px)": { maxHeight: "none" },
  },
  worldHeader: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: space.x3,
    marginBottom: space.x4,
  },
  chatColumn: {
    gap: space.x2,
    display: "flex",
    flexDirection: "column",
    height: "calc(100vh - 190px)",
    minHeight: "440px",
    position: "relative",
  },
  chatScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    paddingRight: space.x2,
  },
  loadMore: {
    textAlign: "center",
    paddingBlock: space.x2,
    fontSize: fontSize.micro,
    color: colors.textMuted,
  },
  jumpToBottom: {
    borderRadius: skin.controlRadius,
    boxShadow: skin.controlShadow,
    fontFamily: fonts.body,
    position: "absolute",
    bottom: "96px",
    left: "50%",
    transform: "translateX(-50%)",
    paddingInline: space.x4,
    paddingBlock: space.x2,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: fontSize.caption,
    cursor: "pointer",
  },
  dicePicker: {
    padding: space.x3,
    borderRadius: radii.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
  },
  diceButton: {
    fontFamily: fonts.numeric,
    borderRadius: skin.controlRadius,
    boxShadow: skin.controlShadow,
    paddingInline: space.x3,
    paddingBlock: space.x2,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: fontSize.caption,
    cursor: "pointer",
    ":hover": { borderColor: colors.accent, color: colors.text },
    ":disabled": { opacity: 0.4, cursor: "not-allowed" },
  },
  avatarImage: {
    width: "32px",
    height: "32px",
    borderRadius: radii.full,
    objectFit: "cover",
    flexShrink: 0,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
  },
  avatarLarge: {
    width: "84px",
    height: "84px",
    borderRadius: radii.md,
    objectFit: "cover",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
  },
  avatarMedium: {
    width: "48px",
    height: "48px",
    borderRadius: radii.full,
    objectFit: "cover",
    flexShrink: 0,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
  },
  avatarPlaceholderMedium: {
    width: "48px",
    height: "48px",
    borderRadius: radii.full,
    backgroundColor: colors.accentMuted,
    color: colors.accent,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: fontWeight.bold,
    flexShrink: 0,
  },
  avatarPlaceholder: {
    width: "84px",
    height: "84px",
    borderRadius: radii.md,
    backgroundColor: colors.surfaceMuted,
    color: colors.textMuted,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: fonts.mono,
    fontSize: fontSize.heading,
  },
});
